### ISSUE TITLE
Additions to README

### ISSUE THREAD

**Issue by madisonkh** [TabiasP/Prometheus#1]
We need more detailed descriptions for the following the README file:

- Story
- Tournament
- Shopping

Maybe make a new section to start describing them and how each will be handled.

**Comment by moriartysara** [comment]
I was a bit confused by this issue as there are already short descriptions for Story, Tournament and Shopping on the README file. I'm posting this here for anyone else who may be confused as well.

We need to come up with some outlines of how the user (or player) interacts with the three modes. 
Maybe we can all share some ideas here to get this README completed in the time allotted.

**Comment by TabiasP** [comment]
@moriartysara You can run the program from the "master" branch and everything is runnable. By analyzing how the game plays out, you should be able to figure out where there is room for improvement. 
But basically we want to expand the current story mode, which only consist of a tutorial. The tournament mode can be discussed further in class, but I have a class setup for that as well. Shopping has a class of it's own as well. It's meant for the user to take his/her money and spend it to purchase potions, weapons and equipment. @hector1995 has already constructed an inventory system in the shopping package. He is still working on implementing it into the actual game itself.

**Comment by moriartysara** [comment]
Thanks! @TabiasP
