### ISSUE TITLE
Implementing Inventory

### ISSUE THREAD

**Issue by moriartysara** [TabiasP/Prometheus#15]
For everyone working who will be implementing the Inventory system we are working on: 

If you plan on implementing it, would you like us to add functionality to the useItem method that is created in the Inventory? If so the useItem method could use items like potions to add health or elixirs to add magic back. 

We would like your opinions so we can finish Inventory allowing @TabiasP and @madisonkh to work on Battle System.

**Comment by TabiasP** [comment]
For the battle system, we will be making use of the inventory system. We need features such as "remove item" and "add item".  We also do need the useItem method, for when the battle is initiated.
