### ISSUE TITLE
Character_Class Developers Issue

### ISSUE THREAD

**Issue by hector1995** [TabiasP/Prometheus#18]
I noticed that there is no health cap. 
I believe this should be implemented because with the inventory, when using potions, it shouldn't allow the user to go over the amount of health they have it isn't a permanent boost item, but it currently does that since the setHealth method does not check and makes sure the user health doesn't go over its max amount.

**Comment by hector1995** [comment]
One solution I have for you is to implement an add() method and then we can use that method instead of the setHealth() to make sure it doesn't go above the max.
You can have something like addHealth(int amt), addMagic(int amt), etc.
And we can use the set methods for items that add a permanent boost towards the player.

**Comment by madisonkh** [comment]
This is just my opinion, and I may have missed something, but the way I see it being implemented at the moment, the cap would _not_ need to be made in the character classes, but instead needs to be managed by whatever class is handling the functionality of the items or the battle. Let's consider a health potion. At the current time, as I understand it, the battle system essentially "copies" the player's health at the start of the battle, and uses that copied value in its calculations. The max health stored in the character object itself isn't touched during the fight. So if anything, a max health value could be implemented into the battle system (essentially, a second copy of the health value that never gets decreased) and handled there (perhaps it calls a method when a health potion is used to increase the health value by returning the value it will heal and decrements the number of potions in the inventory, then the current health value can be compared to the maxHealth value and if health > maxHealth, then health would instead be set to the value of maxHealth).
Permanent boosts through leveling up and the like could be handled through something like add() methods in the character class, though.

**Comment by psloan1995** [comment]
I agree with Madison, the health value of the character should be copied to the battle system, then modified. that way the characters health after each battle defaults back to what is was. in the character class we could change the value of health instead of being a constant to be a equation such as the original  100 + the boost from each level, ie. 100 + 10 for each level the character progresses.

**Comment by psloan1995** [comment]
Something along the lines of

public void setHealth(int h){
		this.health = (h += boost);
	}

**Comment by hector1995** [comment]
#Close
