### ISSUE TITLE
Shopping.java Infinite Loop Bug

### ISSUE THREAD

**Issue by TabiasP** [TabiasP/Prometheus#30]
@Nafruoy There is a bug in the Shopping.java file. Whenever the user enters the shop it is stuck with the following:
Invalid input.
Weapons (1) / Consumables (2) / Exit Store (3)

**Comment by Nafruoy** [comment]
Thank you. I'll get on that.

**Comment by Nafruoy** [comment]
@TabiasP Fixed it. Let me know if anything else pops up.

**Comment by TabiasP** [comment]
@Nafruoy So the issue is that you have an outdated version of the code. Make a merge request and merge the latest updates into your repo. That way you are able to see where the problem is. The infinite loop still exist in the current version of the code.

**Comment by Nafruoy** [comment]
Wow, I'm a moron. It was driving me crazy why I wasn't pulling from the main repo, and why it kept saying auth creds failed or something similar. Turns out I was using the .git link that we copy to clone/download. Not using the actual url of the repo.

**Comment by Nafruoy** [comment]
Anyway pulled from main. Hopefully, I'll get it fixed before sleep.
