### ISSUE TITLE
Multiple remotes in Eclipse

### ISSUE THREAD

**Issue by Nafruoy** [TabiasP/Prometheus#34]
@TabiasP If you know anything about using multiple remotes in Eclipse, please teach me.

**Comment by Nafruoy** [comment]
Cause it was frustrating trying to make sure I can pull from the main repo, but just send to my fork.

**Comment by TabiasP** [comment]
I will show the class on Wednesday the official way to go about these problems, because you're not the only one.

**Comment by Nafruoy** [comment]
I appreciate it.
