### ISSUE TITLE
Shopping.java menu bug

### ISSUE THREAD

**Issue by TabiasP** [TabiasP/Prometheus#35]
@Nafruoy  When selecting the "consumable option" despite the options available, it will always say that you have selected the "Health Potion"

**Comment by Nafruoy** [comment]
On it.

**Comment by Nafruoy** [comment]
didn't change index value. Committing.

**Comment by Nafruoy** [comment]
running it through on my end just to damn freaking sure it works.

**Comment by Nafruoy** [comment]
Seems to be working on my end.

**Comment by TabiasP** [comment]
you can go ahead and make a pull request if that's the case.

**Comment by Nafruoy** [comment]
Little bit of trouble. When I'm trying to make a pull request it says nothing to compare. The only ones that'll compare is when Prototype is base and Master is head, and they're both wrong.

**Comment by TabiasP** [comment]
"master is up to date with all commits from Prototype. Try switching the base for your comparison." Click on the link associate with switching your base, and see what happens.

**Comment by Nafruoy** [comment]
I can still send it, but what I'm seeing is that it'll just give what you already have.

**Comment by Nafruoy** [comment]
@TabiasP Sent it
