### ISSUE TITLE
Alternative Tournament?

### ISSUE THREAD

**Issue by madisonkh** [TabiasP/Prometheus#53]
Instead of trying to adapt the battle system to work for both the story mode and tournament mode, we could consider changing the tournament entirely to be less of a "battle" tournament and more like a card game tournament of sorts (say it takes place in a tavern).

The player can continue playing as long as they want, but at the risk of losing all of their winnings so far in the tournament or losing more money straight from their pockets if they do eventually lose. This risk could also be controlled by a level of "drunkenness" (the player may have the option to get a drink between rounds, resulting in greater potential winnings the more "drunk" they are, but a higher risk as well of losing more money).

The game would still be sort of luck-based, but it would be interactive. It would be similar to the game "21", in which the goal is to get the sum value of the cards you lay down to equal 21, without going over (you win by getting to 21 exactly or when your opponent goes over 21). So both the player and their AI opponent would draw a number of cards (stored in an array for the round) and pick the one they want to place down for each turn. The AI  could use a simple greedy algorithm to make the decision of which one it should put down (it uses the highest card in its "hand" that they can use without going over the target value of 21, along with the cards they've already played), and if it does not have a card that fits the requirements, it instead is forced to play the lowest card and they lose.

Does anyone have any opinions? Would this be a simple, but drastic enough change to make this late to the tournament?

**Comment by moriartysara** [comment]
I think this would be a good addition to the game. If we begin working on this idea soon we could have it implemented by Wednesday.
