### ISSUE TITLE
Character and Enemy classes need cleaning up

### ISSUE THREAD

**Issue by madisonkh** [TabiasP/Prometheus#58]
A lot of the attributes in the character and enemy classes are unnecessary, even with a more complex battle system. We need someone who is responsible for working with those classes to go in and clean them up.

Attributes that need to be deleted (both in Character and Enemy):
- damage
- defense
- boost
- weapon_damage
- intelligence

Strength is staying because it will determine punch strength, and weapon damage and magic damage will be determined by what weapon or spell the player selects. Defense is unnecessary since armor can do its role just fine (physical defense). Resistance could become magic resistance so it can stay for the time being, and speed could be implemented at some point, so it can stay as well.

You will need to clean up both the base classes and each individual derived class.

**Comment by moriartysara** [comment]
I'm working on cleaning them up right now. I should have it done shortly.
